### ISSUE TITLE
Kibana fails to load with this plugin

### ISSUE THREAD

**Issue by rbkumar88** [opendistro-for-elasticsearch/anomaly-detection-kibana-plugin#10]
When I build this plugin and use ```kibana-plugin install``` cmd to install it, kibana fails to start with this error ```Kibana did not load properly. Check the server output for more information.```. When I look at the server logs, I just find this line to be an issue.
```{"type":"response","@timestamp":"2020-03-24T17:50:59Z","tags":[],"pid":1,"method":"get","statusCode":404,"req":{"url":"/built_assets/css/plugins/opendistro-anomaly-detection/app.light.css","method":"get","headers":{"host":"10.16.241.212:31952","connection":"keep-alive","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36","accept":"text/css,*/*;q=0.1","referer":"http://10.16.241.212:31952/login?nextUrl=%2F","accept-encoding":"gzip, deflate","accept-language":"en-US,en;q=0.9"},"remoteAddress":"10.42.10.0","userAgent":"10.42.10.0","referer":"http://10.16.241.212:31952/login?nextUrl=%2F"},"res":{"statusCode":404,"responseTime":2,"contentLength":9},"message":"GET /built_assets/css/plugins/opendistro-anomaly-detection/app.light.css 404 2ms - 9.0B"}```

Any ideas on resolving this?

**Comment by ylwu-amzn** [comment]
We have changed a lot recently. Can you try latest code to check if the problem still exists?

**Comment by ylwu-amzn** [comment]
@rbkumar88 , can we close this question now ?

**Comment by ylwu-amzn** [comment]
Close this issue as no reply for more than 2 months.  Reopen it if you still have problem.
