### ISSUE TITLE
Unhandled promise rejections when calls to retrieve detector state times out

### ISSUE THREAD

**Issue by ohltyler** [opendistro-for-elasticsearch/anomaly-detection-kibana-plugin#114]
When a domain has a large amount of detectors and large anomaly results index, the performance can degrade to the point where calls to retrieve detector state can time out. Calls on the detector list and dashboard pages make expensive calls to retrieve all existing detector states. Because of this, the `Promise.all()` command [here](https://github.com/opendistro-for-elasticsearch/anomaly-detection-kibana-plugin/blob/1.4/server/routes/ad.ts#L468) can throw exceptions that seem to be uncaught, even when encapsulated in a try/catch block. This results in no detectors being shown on the given page.

Chrome devtools when a timeout occurs:
![Screen Shot 2020-05-07 at 5 26 35 PM](https://user-images.githubusercontent.com/62119629/81426119-9ba36300-910d-11ea-8240-3e519159c250.png)

Need to investigate if the issue is caused by this line, or a way to catch exception gracefully and propagate to user why detector's aren't loading properly, etc.

**Comment by ylwu-amzn** [comment]
We definitely need a bulk API to query multiple/all detector's profile info. Or we save profile info in index, so we can search easily. This problem needs both front end and backend changes.

**Comment by ohltyler** [comment]
After investigating more, the issue is more defined in #174. Will close this.
