### ISSUE TITLE
can we use this on aws managed elasticsearch

### ISSUE THREAD

**Issue by rverma-jm** [opendistro-for-elasticsearch/anomaly-detection-kibana-plugin#120]
Wondering if we can enabled this plugin in aws managed elasticsearch 7.4?

**Comment by ylwu-amzn** [comment]
Thanks for your interest. We are working on it, should be available soon.

**Comment by rverma-jm** [comment]
Do you have any roadmap which we can follow.

**Comment by ylwu-amzn** [comment]
Yeah, we are working on the roadmap, will publish it soon.
