### ISSUE TITLE
Some word overlap selected detector

### ISSUE THREAD

**Issue by ylwu-amzn** [opendistro-for-elasticsearch/anomaly-detection-kibana-plugin#127]
When choose one detector on dashboard page, the detector name has overlap with some word.

![Screen Shot 2020-05-11 at 12 17 43 AM](https://user-images.githubusercontent.com/49084640/81534453-e6df9080-931c-11ea-8141-8aa2db5da129.png)

**Comment by ohltyler** [comment]
Can't seem to reproduce this issue anymore, was this a bug with EUI that has been fixed?

**Comment by yizheliu-amazon** [comment]
I think this is EUI bug, instead of our issue. I will close it for now. If it happens again, we can reopen it.
