### ISSUE TITLE
Add batch actions on detector list page

### ISSUE THREAD

**Issue by ylwu-amzn** [opendistro-for-elasticsearch/anomaly-detection-kibana-plugin#144]
Currently, user need to open detector detail page to start/stop/delete detector. If user want to stop multiple detectors, they have to open them one by one and click stop button on detail page. That's really time consuming. 

We can use the similar way to allow user to choose multiple detectors and apply actions to them. Refer to monitor list page design.

![Screen Shot 2020-05-15 at 9 55 47 AM](https://user-images.githubusercontent.com/49084640/82076176-48dc2500-9692-11ea-8d44-b596e71751c9.png)

**Comment by ohltyler** [comment]
Will close this, splitting into 2 issues & PRs
