### ISSUE TITLE
Plugin download link

### ISSUE THREAD

**Issue by sc7565** [opendistro-for-elasticsearch/anomaly-detection-kibana-plugin#149]
Was not able to find, download link? may be documentation is also not updated - https://opendistro.github.io/for-elasticsearch-docs/docs/kibana/plugins/

**Comment by H1L021** [comment]
Is the plugin not yet ready for standalone installation ?

**Comment by sc7565** [comment]
I actually got the link from opendistro-build repo we can close this issue
