### ISSUE TITLE
Error while creating detector

### ISSUE THREAD

**Issue by sc7565** [opendistro-for-elasticsearch/anomaly-detection-kibana-plugin#150]
no handler found for uri [/_opendistro/_anomaly_detection/detectors/_search] and method [POST]

I did confirm ES does have plugin installed 

sh-4.2# ./elasticsearch-plugin list
opendistro-anomaly-detection
opendistro-job-scheduler
opendistro-knn
opendistro_alerting
opendistro_index_management
opendistro_performance_analyzer
opendistro_security
opendistro_sql

Not, sure If I am doing something wrong

![image](https://user-images.githubusercontent.com/23261668/82135090-a8d6e680-97cc-11ea-870f-afe7fa59f526.png)

**Comment by ohltyler** [comment]
Hello, could you let me know how you currently have ES and Kibana installed and running? If you want to use a stable version of this plugin along with the other Open Distro for Elasticsearch plugins, I recommend installing using one of the methods listed here: https://opendistro.github.io/for-elasticsearch-docs/docs/install/

**Comment by sc7565** [comment]
I am using Repo - https://github.com/opendistro-for-elasticsearch/opendistro-build to create my images which are pushed under rbmconnect docker handler.

Seems the plugin is installed in both ES and kibana successfully looking at build logs, but for some reason kibana show above error and you cannot create a detctor.

**Comment by ohltyler** [comment]
Have you tried other Kibana plugins to see if they are having any problems connecting with their corresponding ES plugins?

If the issue is only with this particular plugin, there might be an issue regarding the ordering in which plugins are installed on Elasticsearch; this is because the anomaly detection ES plugin is dependent on the job scheduler ES plugin being installed first. @weicongs-amazon do you know if this could be a possible issue in the opendistro-build repo?

**Comment by sc7565** [comment]
So, I did see that issue earlier and copied the plugins with 1_*, 2_* .. thus installing plugin in sequence.

`Step 20/49 : RUN curl -fsSL https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.6.1-linux-x86_64.tar.gz |     tar zx --strip-components=1
 ---> Running in 19eab36fa178
Removing intermediate container 19eab36fa178
 ---> d5024ad18463
Step 21/49 : RUN set -ex && for esdirs in config data logs; do         mkdir -p "$esdirs";     done
 ---> Running in 40476e9cef96
+ for esdirs in config data logs
+ mkdir -p config
+ for esdirs in config data logs
+ mkdir -p data
+ for esdirs in config data logs
+ mkdir -p logs
Removing intermediate container 40476e9cef96
 ---> b8eb55a8da47
Step 22/49 : RUN for plugin_path in `ls /tmp/plugins/`; do       elasticsearch-plugin install --batch file:/tmp/plugins/$plugin_path;     done
 ---> Running in c81c1f1a2d7d
-> Installing file:/tmp/plugins/1_opendistro_sql.zip
-> Downloading file:/tmp/plugins/1_opendistro_sql.zip
-> Installed opendistro_sql
-> Installing file:/tmp/plugins/2_opendistro_alerting.zip
-> Downloading file:/tmp/plugins/2_opendistro_alerting.zip
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@     WARNING: plugin requires additional permissions     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
* java.lang.RuntimePermission createClassLoader
* java.lang.RuntimePermission getClassLoader
* java.net.NetPermission getProxySelector
* java.net.SocketPermission * connect,resolve
See http://docs.oracle.com/javase/8/docs/technotes/guides/security/permissions.html
for descriptions of what these permissions allow and the associated risks.
-> Installed opendistro_alerting
-> Installing file:/tmp/plugins/3_opendistro-job-scheduler.zip
-> Downloading file:/tmp/plugins/3_opendistro-job-scheduler.zip
-> Installed opendistro-job-scheduler
-> Installing file:/tmp/plugins/4_opendistro_security.zip
-> Downloading file:/tmp/plugins/4_opendistro_security.zip
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@     WARNING: plugin requires additional permissions     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
* java.io.FilePermission /proc/sys/net/core/somaxconn#plus read
* java.lang.RuntimePermission accessClassInPackage.com.sun.jndi.ldap
* java.lang.RuntimePermission accessClassInPackage.sun.misc
* java.lang.RuntimePermission accessClassInPackage.sun.nio.ch
* java.lang.RuntimePermission accessClassInPackage.sun.security.x509
* java.lang.RuntimePermission accessDeclaredMembers
* java.lang.RuntimePermission accessUserInformation
* java.lang.RuntimePermission createClassLoader
* java.lang.RuntimePermission getClassLoader
* java.lang.RuntimePermission setContextClassLoader
* java.lang.RuntimePermission shutdownHooks
* java.lang.reflect.ReflectPermission suppressAccessChecks
* java.net.NetPermission getNetworkInformation
* java.net.NetPermission getProxySelector
* java.net.SocketPermission * connect,accept,resolve
* java.security.SecurityPermission getProperty.ssl.KeyManagerFactory.algorithm
* java.security.SecurityPermission insertProvider.BC
* java.security.SecurityPermission org.apache.xml.security.register
* java.security.SecurityPermission putProviderProperty.BC
* java.security.SecurityPermission setProperty.ocsp.enable
* java.util.PropertyPermission * read,write
* java.util.PropertyPermission org.apache.xml.security.ignoreLineBreaks write
* javax.security.auth.AuthPermission doAs
* javax.security.auth.AuthPermission modifyPrivateCredentials
* javax.security.auth.kerberos.ServicePermission * accept
See http://docs.oracle.com/javase/8/docs/technotes/guides/security/permissions.html
for descriptions of what these permissions allow and the associated risks.
-> Installed opendistro_security
-> Installing file:/tmp/plugins/5_opendistro_performance_analyze.zip
-> Downloading file:/tmp/plugins/5_opendistro_performance_analyze.zip
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@     WARNING: plugin requires additional permissions     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
* com.sun.tools.attach.AttachPermission attachVirtualMachine
* com.sun.tools.attach.AttachPermission createAttachProvider
* java.io.FilePermission /-#plus read,write,execute,delete,readlink
* java.lang.RuntimePermission accessClassInPackage.jdk.internal.misc
* java.lang.RuntimePermission accessClassInPackage.sun.tools.attach
* java.lang.RuntimePermission accessDeclaredMembers
* java.lang.RuntimePermission loadLibrary.attach
* java.lang.RuntimePermission manageProcess
* java.lang.reflect.ReflectPermission suppressAccessChecks
See http://docs.oracle.com/javase/8/docs/technotes/guides/security/permissions.html
for descriptions of what these permissions allow and the associated risks.
-> Installed opendistro_performance_analyzer
-> Installing file:/tmp/plugins/6_opendistro_index_management.zip
-> Downloading file:/tmp/plugins/6_opendistro_index_management.zip
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@     WARNING: plugin requires additional permissions     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
* java.lang.RuntimePermission createClassLoader
* java.lang.RuntimePermission getClassLoader
* java.net.NetPermission getProxySelector
* java.net.SocketPermission * connect,resolve
See http://docs.oracle.com/javase/8/docs/technotes/guides/security/permissions.html
for descriptions of what these permissions allow and the associated risks.
-> Installed opendistro_index_management
-> Installing file:/tmp/plugins/7_opendistro-knn.zip
-> Downloading file:/tmp/plugins/7_opendistro-knn.zip
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@     WARNING: plugin requires additional permissions     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
* java.lang.RuntimePermission loadLibrary.KNNIndexV1_7_3_6
See http://docs.oracle.com/javase/8/docs/technotes/guides/security/permissions.html
for descriptions of what these permissions allow and the associated risks.
-> Installed opendistro-knn
-> Installing file:/tmp/plugins/8_opendistro-anomaly-detection.zip
-> Downloading file:/tmp/plugins/8_opendistro-anomaly-detection.zip
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@     WARNING: plugin requires additional permissions     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
* java.lang.RuntimePermission accessClassInPackage.sun.misc
* java.lang.RuntimePermission accessDeclaredMembers
* java.lang.reflect.ReflectPermission suppressAccessChecks
See http://docs.oracle.com/javase/8/docs/technotes/guides/security/permissions.html
for descriptions of what these permissions allow and the associated risks.
-> Installed opendistro-anomaly-detection
Removing intermediate container c81c1f1a2d7d
 ---> 879643954a07
`

**Comment by sc7565** [comment]
May be I have not installed plugins properly, but UI does not show much errors

```
},"res":{"statusCode":200,"responseTime":10,"contentLength":9},"message":"POST /api/alerting/_search 200 10ms - 9.0B"}
Alerting - MonitorService - createMonitor: { Error: [search_phase_execution_exception] all shards failed
    at respond (/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:349:15)
    at checkRespForFailure (/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:306:7)
    at HttpConnector.<anonymous> (/usr/share/kibana/node_modules/elasticsearch/src/lib/connectors/http.js:173:7)
    at IncomingMessage.wrapper (/usr/share/kibana/node_modules/elasticsearch/node_modules/lodash/lodash.js:4929:19)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  status: 503,
  displayName: 'ServiceUnavailable',
  message: '[search_phase_execution_exception] all shards failed',
  path: '/_opendistro/_alerting/monitors?refresh=wait_for',
  query: {},
  body:
   { error:
      { root_cause: [],
        type: 'search_phase_execution_exception',
        reason: 'all shards failed',
        phase: 'query',
        grouped: true,
        failed_shards: [] },
     status: 503 },
  statusCode: 503,
  response:
   '{"error":{"root_cause":[],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[]},"status":503}',
  toString: [Function],
  toJSON: [Function] }```

**Comment by ohltyler** [comment]
Okay, I see. I'm still not sure how exactly you set that up using the opendistro-build repository so it's hard to tell where the issue may be there. That repository might be unstable at the moment as we are in the middle of upgrading to be compatible with ES/Kibana 7.7.0. If you want to run a stable version of all of the plugins (including anomaly detection) I would recommend using and modifying the example docker-compose file [here](https://opendistro.github.io/for-elasticsearch-docs/docs/install/docker/#sample-docker-compose-file). This way, all you have to do is
1. Copy and save the docker-compose file 
1. run `docker pull` to pull the stable ES and Kibana images (found at the top of the page [here](https://opendistro.github.io/for-elasticsearch-docs/docs/install/docker/))
2. Run `docker-compose up` to boot up the entire stack.

**Comment by sc7565** [comment]
You can close this, rebooted the cluster and it started working
