### ISSUE TITLE
Cannot create detector for Anomaly Detection

### ISSUE THREAD

**Issue by antonisnyc94** [opendistro-for-elasticsearch/anomaly-detection-kibana-plugin#167]
Whenever I am trying to create a detector in Kibana I'm getting the following error. I have rpm installations of open-distro on CIS Benchmarked Amazon Linux 2 AMI.

I assume it has to do with the API not functioning for some reason but i dont know how to troubleshoot.

no handler found for uri [/_opendistro/_anomaly_detection/detectors/_search] and method [POST]

![image](https://user-images.githubusercontent.com/36517441/82469177-afe24b00-9a91-11ea-882e-10d36995aed8.png)

**Comment by ylwu-amzn** [comment]
Tested with Amazon Linux 2 AMI `t2.2xlarge`, couldn't reproduce your problem. Did you follow this document https://opendistro.github.io/for-elasticsearch-docs/docs/install/rpm/ ?

Can you explain the detail steps to reproduce this problem?

**Comment by antonisnyc94** [comment]
Hello,

Thanks for your quick reply! First of all, i have an elasticsearch cluster of 3 instances, and secondly I followed the upgrade guide in the opendistro documentation to upgrade from 1.6 to 1.7. I restarted the cluster couple of times but no luck. Can I use any GET requests in the dev plugin for seeing if the api is responsive at all?

Thanks,
Tony

**Comment by ylwu-amzn** [comment]
Got it. Can you try any APIs on Kibana dev tools? Refer to this doc https://opendistro.github.io/for-elasticsearch-docs/docs/ad/api/

**Comment by antonisnyc94** [comment]
I am getting security exceptions but i know for sure that this is not the case since my current account has admin rights for everything. It appears that the API is inaccessible, i can confirm it by checking the results of the last screenshot, as it throws security exceptions for none existing requests. What would you recommend from here?

![image](https://user-images.githubusercontent.com/36517441/82492116-acf85200-9ab3-11ea-95a8-6251d70e8350.png)

![image](https://user-images.githubusercontent.com/36517441/82491792-2479b180-9ab3-11ea-9ad3-8f8f735a3f00.png)

![image](https://user-images.githubusercontent.com/36517441/82492310-fd6faf80-9ab3-11ea-92ca-1e5d58edd5a7.png)

![image](https://user-images.githubusercontent.com/36517441/82492448-39a31000-9ab4-11ea-81bc-3670fb498cc2.png)

Regards,
Tony

**Comment by ylwu-amzn** [comment]
Need some time to reproduce this problem by upgrading from 1.6 to 1.7 and investigate. If urgent, can you just create domain with 1.7 ? Guess it's caused by upgrading.

**Comment by ylwu-amzn** [comment]
Seems similar issue https://github.com/opendistro-for-elasticsearch/anomaly-detection-kibana-plugin/issues/150,

Can you try this solution?
> You can close this, rebooted the cluster and it started working

**Comment by antonisnyc94** [comment]
For some reason the plugin wasnt installed during the upgrade. I will try and install it and get back to you.

![image](https://user-images.githubusercontent.com/36517441/82673200-7899a880-9c0f-11ea-8099-2f37dcda50d5.png)

**Comment by antonisnyc94** [comment]
I havent seen any documentation on how to install the plugin alone. All i see is how to install builds for new clusters. Am I missing something? Do you recommend something else?

Thanks,
Tony

**Comment by ylwu-amzn** [comment]
Can you try this? https://opendistro.github.io/for-elasticsearch-docs/docs/install/plugins/#anomaly-detection

**Comment by antonisnyc94** [comment]
That was it. Thanks a lot!
