### ISSUE TITLE
Pagination not displaying properly on anomaly results table

### ISSUE THREAD

**Issue by ohltyler** [opendistro-for-elasticsearch/anomaly-detection-kibana-plugin#179]
When the page count > 1 for the anomaly results table, the top pagination doesn't display all pages; always just shows 1 page. Change to be consistent with table's bottom pagination:

![Screen Shot 2020-05-26 at 9 45 33 AM](https://user-images.githubusercontent.com/62119629/82927707-f7575400-9f35-11ea-8e5e-1516e3d1b9af.png)

**Comment by ylwu-amzn** [comment]
Seems related with version upgrade, check on our test domain, the top pagination will not show.

![Screen Shot 2020-05-26 at 10 01 44 AM](https://user-images.githubusercontent.com/49084640/82929099-fde6cb00-9f37-11ea-9398-f34e6015d330.png)

**Comment by ohltyler** [comment]
I think the issue is this: when upgrading from 7.4.x -> 7.6.x, a change was introduced where pagination always shows, even if only one page. Looks like the pagination has always had a bug of not working right, it was just hidden before since it never was showing.
