### ISSUE TITLE
Add delete batch action on detector list page

### ISSUE THREAD

**Issue by ohltyler** [opendistro-for-elasticsearch/anomaly-detection-kibana-plugin#194]
Add a delete batch action similar to the implemented start/stop batch actions on the detector list page. Add the 'type delete to confirm' functionality similar to the modal when a user wants to delete a detector from the detector details pages.

**Comment by ylwu-amzn** [comment]
> Add a stop batch action similar to the implemented start/stop batch actions on the detector list page.

You mean add a **delete** batch action?

**Comment by ohltyler** [comment]
> > Add a stop batch action similar to the implemented start/stop batch actions on the detector list page.
> 
> You mean add a **delete** batch action?

Yes, my mistake
