### ISSUE TITLE
Search with a longer time interval than 7 days

### ISSUE THREAD

**Issue by amirmuminovic** [opendistro-for-elasticsearch/anomaly-detection-kibana-plugin#21]
Whenever I try to search for anomalies, the maximum duration is around 7 days. Is there any way to increase the interval on the frontend?

**Comment by ylwu-amzn** [comment]
You mean "Detector output" on "Model definitions" page? That's sample result for historical data. We limit the date range as 5 days currently. These are **sample** data which show how the model will look like if applied to historical data.  You can check **real** anomaly result on "Anomalies" page.

**Comment by amirmuminovic** [comment]
Thank you for the clarification @ylwu-amzn . Just to verify, you are saying that that real anomaly detection uses all data, not just in the data range of 5 days?

**Comment by amirmuminovic** [comment]
I've found the answer in the documentation. All data is used. Thank you again @ylwu-amzn for the explanation.
