### ISSUE TITLE
Can I choose remote cluster indices for anomaly detection?

### ISSUE THREAD

**Issue by HagunKim** [opendistro-for-elasticsearch/anomaly-detection-kibana-plugin#215]
I'd like to use anomaly-detection plugin for other ES cluster connected remote cluster configuration.
In Kibana, I can use discover or something using search with the remote cluster(cross cluster search), but anomaly-detection doesn't support it.
Is it possible to use cross cluster indices for anomaly detection in kibana?

**Comment by ylwu-amzn** [comment]
> I'd like to use anomaly-detection plugin for other ES cluster connected remote cluster configuration.
> In Kibana, I can use discover or something using search with the remote cluster(cross cluster search), but anomaly-detection doesn't support it.
> Is it possible to use cross cluster indices for anomaly detection in kibana?

Can you explain more about what you want for `use cross cluster indices for anomaly detection in kibana`?

As kaituo said, we don't support this feature in kibana now. Can you try [create detector API](https://opendistro.github.io/for-elasticsearch-docs/docs/ad/api/#create-anomaly-detector) ?

**Comment by HagunKim** [comment]
@kaituo, @ylwu-amzn, Thanks for your reply! For now, when I try to create detector on Kibana, In dropdown list for index, I can only choose indices of ES that is connected directly.
I want to see and choose my Kibana index patterns containing cross cluster indices or the cross cluster indices themselves on the dropdown list.
Could you consider this modifications?

**Comment by ylwu-amzn** [comment]
Thanks @HagunKim, sure, that's good suggestion. Have you tried [create detector API](https://opendistro.github.io/for-elasticsearch-docs/docs/ad/api/#create-anomaly-detector)?

**Comment by HagunKim** [comment]
@ylwu-amzn , I tried create detector API with remote cluster indices via Kiabana Dev Tools menu. And it worked. I got 201 response and I saw the detector on Kibana. When I tried to create using non-existing index, it returned error with 404 response.

**Comment by ylwu-amzn** [comment]
> @ylwu-amzn , I tried create detector API with remote cluster indices via Kiabana Dev Tools menu. And it worked. I got 201 response and I saw the detector on Kibana. When I tried to create using non-existing index, it returned error with 404 response.

Cool, thanks @HagunKim. I created a feature issue to track this requirement https://github.com/opendistro-for-elasticsearch/anomaly-detection-kibana-plugin/issues/220,  Feel free to add your suggestion there. 

If no more questions, how about we close this question issue?

**Comment by HagunKim** [comment]
@ylwu-amzn, Thanks. I agree with you. I hope I can see that feature soon.
