### ISSUE TITLE
Improve sunburst chart for Anomaly Distribution

### ISSUE THREAD

**Issue by yizheliu-amazon** [opendistro-for-elasticsearch/anomaly-detection-kibana-plugin#24]
Given only 1 detector exists, the inside Index circle will have issue in following scenarios:
1. if Linked Label is configured for identifying index, label of Index circle will be invisible;
1. if Fill Label is configured for identifying index, label of it will be overlapped with outer Detector circle

**Screenshot of 1st scenario:**
![Screen Shot 2020-04-15 at 3 28 31 PM](https://user-images.githubusercontent.com/59710443/79395189-fb06bc80-7f2d-11ea-9f0f-5e264937a6d2.png)

**Screenshot of 2nd scenario**:
![Screen Shot 2020-04-15 at 3 25 09 PM](https://user-images.githubusercontent.com/59710443/79394886-57b5a780-7f2d-11ea-903a-5b4bdd854fcb.png)

We think currently it is fine because sunburst chart does not make big difference if there is only 1 detector + 1 index. We will keep digging into this, and may open issue for [elastic-chart](https://github.com/elastic/elastic-charts) to see if we are using it in a correct way or it is bug of the library.

**Comment by yizheliu-amazon** [comment]
we are also seeing the same issue: https://github.com/elastic/elastic-charts/issues/633

**Comment by yizheliu-amazon** [comment]
Opened issue to owner of elastic-charts: https://github.com/elastic/elastic-charts/issues/637

**Comment by ylwu-amzn** [comment]
Test on 7.7, one detector looks like this
![Screen Shot 2020-06-23 at 10 28 03 AM](https://user-images.githubusercontent.com/49084640/85435409-434ce700-b53c-11ea-8c17-25e64a6089f6.png)

**Comment by yizheliu-amazon** [comment]
Closed by this PR: https://github.com/opendistro-for-elasticsearch/anomaly-detection-kibana-plugin/pull/260
