### ISSUE TITLE
After zoom in, anomaly history chart show empty data

### ISSUE THREAD

**Issue by yizheliu-amazon** [opendistro-for-elasticsearch/anomaly-detection-kibana-plugin#257]
When using mouse to zoom in, anomaly chart on detector result page becomes empty, but it doesn't have this issue if date range is changed using date picker

![Screen Shot 2020-07-16 at 10 36 42 PM](https://user-images.githubusercontent.com/59710443/87752329-f8c62f80-c7b4-11ea-866d-85b2b89fe8eb.png)

**Comment by ylwu-amzn** [comment]
We are using older version of Elastic charts. Kibana 7.8 is using 19.2.0, which changed the zoom in API interface. Will upgrade Elastic charts to 19.2.0 and fix the zoom API.
