### ISSUE TITLE
filter query in anomaly detector object for preview

### ISSUE THREAD

**Issue by wnbts** [opendistro-for-elasticsearch/anomaly-detection-kibana-plugin#258]
The issue https://github.com/opendistro-for-elasticsearch/anomaly-detection/issues/192 was initially reported to anomaly detection backend.

The issue can be reproduced. Using metricbeat as example,

The filterQuery field in the anomaly detector for preview looks like this.
```
"filterQuery": {
	"bool": {
		"filter": [{
			"term": {
				"host.name": {
					"value": "uuid",
					"boost": 1
				}
			}
		}],
		"adjust_pure_negative": true,
		"boost": 1
	}
}
```

On the backend, notice the field name changes from `host.name` to `host_name` on the backend.

```
"filter_query": {
	"bool": {
		"filter": [{
			"term": {
				"host_name": {
					"value": "uuid",
					"boost": 1
				}
			}
		}],
		"adjust_pure_negative": true,
		"boost": 1
	}
}
```

Although browser console may show that the correct field `host.name` is sent, the server side log shows `host_name` is received. I checked the original tcp data and os network shows the `host_name` is sent. So the conclusion is this is more likely a kibana issue.

It is also unknown whether this issue is limited to a specific field or how widespread it is. A code auditing might be necessary.

**Comment by ylwu-amzn** [comment]
Thanks for reporting this problem @wnbts . Will check related code.

**Comment by ylwu-amzn** [comment]
Can you share the test index mapping and some test data? So I can reproduce the issue and debug.

**Comment by wnbts** [comment]
The easiest way to get the data is to generate using metricbeat. An example configuration is in the initial issue.

**Comment by ylwu-amzn** [comment]
@wnbts , I can't reproduce this problem locally
![test-bug](https://user-images.githubusercontent.com/49084640/89607032-5edb2b00-d826-11ea-9860-952c115d72fa.gif)

"filter_query" : {
      "bool" : {
        "filter" : [
          {
            "term" : {
              "host.name" : {
                "value" : "myserver",
                "boost" : 1.0
              }
            }
          }
        ],
        "adjust_pure_negative" : true,
        "boost" : 1.0
      }
    },

**Comment by wnbts** [comment]
Is preview verified? The described issue occurs with preview.

**Comment by ylwu-amzn** [comment]
Can't get data for preview. I start the detector, it can get feature data correctly. Maybe preview function has some problem, will deep dive. 

My detector config (hide my host name with XXX)

```
{
  "name": "test1",
  "description": "test",
  "time_field": "@timestamp",
  "indices": [
    "metricbeat-7.8.1"
  ],
  "filter_query": {
    "bool": {
      "filter": [
        {
          "term": {
            "host.name": {
              "value": "XXX",
              "boost": 1
            }
          }
        }
      ],
      "adjust_pure_negative": true,
      "boost": 1
    }
  },
  "detection_interval": {
    "period": {
      "interval": 1,
      "unit": "Minutes"
    }
  },
  "window_delay": {
    "period": {
      "interval": 1,
      "unit": "Minutes"
    }
  },
  "schema_version": 0,
  "feature_attributes": [
    {
      "feature_id": "f5YEynMBq8uxmKRJv0uv",
      "feature_name": "F1",
      "feature_enabled": true,
      "aggregation_query": {
        "f_1": {
          "sum": {
            "field": "system.cpu.cores"
          }
        }
      }
    }
  ],
  "ui_metadata": {
    "features": {
      "F1": {
        "aggregationBy": "sum",
        "aggregationOf": "system.cpu.cores",
        "featureType": "simple_aggs"
      }
    },
    "filters": [
      {
        "fieldInfo": [
          {
            "label": "host.name",
            "type": "keyword"
          }
        ],
        "fieldValue": "XXX",
        "operator": "is"
      }
    ],
    "filterType": "simple_filter"
  },
  "last_update_time": 1596822494301
}
```

![Screen Shot 2020-08-07 at 10 56 22 AM](https://user-images.githubusercontent.com/49084640/89674301-c2a03b00-d89c-11ea-8ede-5ec632b1342a.png)

**Comment by ylwu-amzn** [comment]
In my testing, I only have about 1 hour's data in metricbeat index. So FeatureManager uses sample ranges and found no data. Refer to code https://github.com/opendistro-for-elasticsearch/anomaly-detection/blob/master/src/main/java/com/amazon/opendistroforelasticsearch/ad/feature/FeatureManager.java#L542-L544, and https://github.com/opendistro-for-elasticsearch/anomaly-detection/blob/master/src/main/java/com/amazon/opendistroforelasticsearch/ad/feature/FeatureManager.java#L491

**Comment by wnbts** [comment]
The issue is, as pointed out in the description, with the preview requests sent from web ui to the backend. Please read the description again.

The issue occurs regardless of the amount of data. Checking the received request or query results is sufficient to show.
