### ISSUE TITLE
Add support for "View Full Screen" for Dashboard Live chart

### ISSUE THREAD

**Issue by yizheliu-amazon** [opendistro-for-elasticsearch/anomaly-detection-kibana-plugin#26]
Add support for "View Full Screen" for Dashboard Live chart

**Comment by mihirsoni** [comment]
Should we create different issue for managing performance for the live chart ?

**Comment by yizheliu-amazon** [comment]
> Should we create different issue for managing performance for the live chart ?

Can you elaborate what is the performance issue for live chart?
