### ISSUE TITLE
Add UT for Dashboard related pages

### ISSUE THREAD

**Issue by yizheliu-amazon** [opendistro-for-elasticsearch/anomaly-detection-kibana-plugin#27]
Add UT for Dashboard related pages

**Comment by ohltyler** [comment]
@yizheliu-amazon did you want to take a look at this? I'm happy to as well, just let me know. Feels like this is necessary and will highly increase code coverage %

**Comment by yizheliu-amazon** [comment]
@ohltyler Thanks for offering help. I will start working on this very likely next sprint. Right now I am collecting data of test coverage for each file, and will create issues to distribute tasks of increasing coverage.

**Comment by ohltyler** [comment]
Will close, since we will use #191 as our main issue regarding code coverage / adding UT
