### ISSUE TITLE
Show action item for invalid query

### ISSUE THREAD

**Issue by kaituo** [opendistro-for-elasticsearch/anomaly-detection-kibana-plugin#281]
We show action item when a detector is stopped.   I added a new cause of stopping detector: https://github.com/opendistro-for-elasticsearch/anomaly-detection/blob/92a586718f93a9ab934169cab0aca42c8641f4d9/src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/AnomalyResultTransportAction.java#L187

The action item is asking cx to revise their query.  We need to reflect this in our call out.

**Comment by ohltyler** [comment]
Closed by #285
