### ISSUE TITLE
Improve AnomalyHistory Chart performance for HC detector

### ISSUE THREAD

**Issue by yizheliu-amazon** [opendistro-for-elasticsearch/anomaly-detection-kibana-plugin#313]
Currently for long date range result in AnomalyHistoryChart, we use bucketized query, which split time range into up to 1000 windows, and only takes max anomaly grade in each small time window(across multiple intervals). Query is like [this](https://github.com/opendistro-for-elasticsearch/anomaly-detection-kibana-plugin/blob/master/public/pages/utils/anomalyResultUtils.ts#L349-L399). The benefit of it is that we can have up to only 1000 points even for long date range, and it can have good performance for rendering; downside of it is it can miss anomalies if in the small time window there are more than 1 anomaly results. 

For HC detector heatmap, we need to show accurate occurrence/count of anomalies for each cell, but such bucketized query can give us less anomalies than actual number. 

Current implementation is to get raw anomaly results, i.e. all results in the date range, but this can potentially bring in performance issue. Need to have better implementation for this.

**Comment by ohltyler** [comment]
@yizheliu-amazon based on #350 can this be closed?

**Comment by yizheliu-amazon** [comment]
Thanks for catching this. Yes. It can be closed.
