### ISSUE TITLE
upgrade dependency ua-parser-js-0.7.21.tgz

### ISSUE THREAD

**Issue by vamshin** [opendistro-for-elasticsearch/anomaly-detection-kibana-plugin#331]
Upgrade to version 0.7.22

**Comment by yizheliu-amazon** [comment]
Hey Vamshi, [the security vulnerability in AD Kibana](https://github.com/opendistro-for-elasticsearch/anomaly-detection-kibana-plugin/network/alerts) I can see only is related to [node-fetch](https://github.com/opendistro-for-elasticsearch/anomaly-detection-kibana-plugin/network/alert/yarn.lock/node-fetch/open), and ua-parser-js is already using [0.7.22](https://github.com/opendistro-for-elasticsearch/anomaly-detection-kibana-plugin/blob/14168a737f361203d0b2434006b04d55c65c0dfd/yarn.lock#L7251), I will close this one in favor of #333
