### ISSUE TITLE
Can't add feature for the detector when users use AD first time

### ISSUE THREAD

**Issue by weicongs-amazon** [opendistro-for-elasticsearch/anomaly-detection-kibana-plugin#342]
### ODFE Version ###
1.12.0

### Distributions ###
All: Docker, RPM, Tar, Deb

### Issue Description ###
After one new ODFE cluster is set up, customer uses the kibana AD UI to create a new detector. The detector can be created successfully, but when customer tries to add new feature, and it will always fail with error message
```
Cannot create anomaly detector with name [test-1] as it's already used by detector [u4Z5RHYBNpJRqK5Wectv]
```

After this detector is deleted, everything works well with new detectors.
### How to reproduce it ###
* Create a new ODFE cluster
* Add kibana sample log data
* create a new detector
* add a new feature

### Isse Severity ###
Not urgent since customer can delete the first detector and then everything works well

**Comment by ohltyler** [comment]
Fixed by #353, closing.
