### ISSUE TITLE
Overlap between anomaly bars in live anomaly chart

### ISSUE THREAD

**Issue by ylwu-amzn** [opendistro-for-elasticsearch/anomaly-detection-kibana-plugin#348]
We will show live anomaly on AD detail page. If there are consecutive anomalies, the bars will have overlap. 

![Screen Shot 2020-12-15 at 9 58 11 AM](https://user-images.githubusercontent.com/49084640/102254222-38f12180-3ebd-11eb-84a5-ff02940ac61b.png)

**Comment by ohltyler** [comment]
Looking into this.
