### ISSUE TITLE
historical detector: show readable error message when there is no historical data

### ISSUE THREAD

**Issue by ylwu-amzn** [opendistro-for-elasticsearch/anomaly-detection-kibana-plugin#361]
When there is no data in historical detection date range, historical detector task will throw ResourceNotFoundException and write such error message in AD task: `There is no data in the detection date range` . But we will show `Unexpected failure ` on historical detector detail page. Suggest to show a more readable error message

**Comment by ohltyler** [comment]
Taking a look. Having discussions on the idea of adding an additional 'No data' state (or something similar) for historical detectors.
