### ISSUE TITLE
Use same color for detector state on detector detail and list page

### ISSUE THREAD

**Issue by ylwu-amzn** [opendistro-for-elasticsearch/anomaly-detection-kibana-plugin#56]
https://github.com/opendistro-for-elasticsearch/anomaly-detection-kibana-plugin/pull/54/files

From @ohltyler 

>can use the `DETECTOR_STATE_COLORS` enum here for consistency w/ detector list page. can call `stateToColorMap(detector.curState)` to retrieve the color

**Comment by yizheliu-amazon** [comment]
Looks like they are same now:

DetectorDetails: https://github.com/opendistro-for-elasticsearch/anomaly-detection-kibana-plugin/blob/master/public/pages/DetectorDetail/containers/DetectorDetail.tsx#L273-L287

https://github.com/opendistro-for-elasticsearch/anomaly-detection-kibana-plugin/blob/master/public/pages/utils/constants.ts#L19-L26

Should be good to close.
