### ISSUE TITLE
Investigate why CodeModal.test.tsx.snap has empty div block

### ISSUE THREAD

**Issue by kaituo** [opendistro-for-elasticsearch/anomaly-detection-kibana-plugin#58]

**Comment by ohltyler** [comment]
@kaituo I ran into similar issues when trying to use snapshots for batch action modals, seems to be some issues with jest snapshot modal rendering in react. I ended up creating tests without using snapshot - maybe you could do that or create a new issue to add test cases for CodeModal?

**Comment by kaituo** [comment]
Yes, close this issue now.
