### ISSUE TITLE
Unit test workflow failing when running yarn kbn bootstrap

### ISSUE THREAD

**Issue by ohltyler** [opendistro-for-elasticsearch/anomaly-detection-kibana-plugin#75]
When looking at the logs of the failed GitHub actions, after running `yarn kbn bootstrap`:

`error An unexpected error occurred: "ENOENT: no such file or directory, lstat '/home/runner/work/anomaly-detection-kibana-plugin/anomaly-detection-kibana-plugin/kibana/packages/kbn-plugin-helpers/node_modules/which'".`

I've had this happen to me before locally, seemed to be fixed when running `yarn kbn bootstrap` a second time. Need to investigate

**Comment by ohltyler** [comment]
Changes have been addressed to remediate the issue for now. See https://github.com/opendistro-for-elasticsearch/anomaly-detection-kibana-plugin/pull/104. Will remove bug label.

**Comment by ohltyler** [comment]
After revisiting, I may have fixed the issue. I ran [yarn upgrade](https://classic.yarnpkg.com/en/docs/cli/upgrade/) to update all dependencies. Seems to not run into errors as mentioned above. Tested out workflow that only runs `yarn kbn bootstrap` once, is passing now. See successful workflow [here](https://github.com/ohltyler/anomaly-detection-kibana-plugin/runs/754868897?check_suite_focus=true)

**Comment by ylwu-amzn** [comment]
Cool, that's great.
